toosistemadeventas_homepage:
    path:     /hello/{name}
    defaults: { _controller: toosistemadeventasBundle:Default:index }

toosistemadeventas_inicio:
    path:     /inicio
    defaults: { _controller: toosistemadeventasBundle:Default:inicio }

toosistemadeventas_promociones:
    path:     /promociones
    defaults: { _controller: toosistemadeventasBundle:Default:promociones }

toosistemadeventas_registro:
    path:     /registro
    defaults: { _controller: toosistemadeventasBundle:Seguridad:registro }

login_form:
    path:     /login
    defaults: { _controller: toosistemadeventasBundle:Security:login }

logout:
    path:     /logout
    defaults: { _controller: toosistemadeventasBundle:Security:logout }

catalogo:
    path:     /catalogo
    defaults: { _controller: toosistemadeventasBundle:Default:catalogo }


inicioAdmin:
    path:     /inicioAdmin
    defaults: { _controller: toosistemadeventasBundle:Usuario:index }

productos:
    path:     /productos
    defaults: { _controller: toosistemadeventasBundle:Productos:productos }

crudUsuarios:
    path:     /crudUsuarios
    defaults: { _controller: toosistemadeventasBundle:Usuario:usuarios }

crudAdmin:
    path:     /crudAdmin
    defaults: { _controller: toosistemadeventasBundle:Usuario:admin }

crudClientes:
    path:     /crudClientes
    defaults: { _controller: toosistemadeventasBundle:Usuario:clientes }

allUsuarios:
    path:     /allUsuarios
    defaults: { _controller: toosistemadeventasBundle:Usuario:all }

nuevoAdmin:
    path:     /nuevoAdmin
    defaults: { _controller: toosistemadeventasBundle:Usuario:nuevoAdmin }

nuevoCliente:
    path:     /nuevoCliente
    defaults: { _controller: toosistemadeventasBundle:Usuario:nuevoCliente }

editarUsuario:
    path:     /editarUsuario/{idUsu}
    defaults: { _controller: toosistemadeventasBundle:Usuario:editarUsuario }

editarAdmin:
    path:     /editarAdmin/{idUsu}
    defaults: { _controller: toosistemadeventasBundle:Usuario:editarAdmin }

editarCliente:
    path:     /editarCliente/{idUsu}
    defaults: { _controller: toosistemadeventasBundle:Usuario:editarCliente}

deleteUsuario:
    path:     /deleteUsuario/{idUsu}
    defaults: { _controller: toosistemadeventasBundle:Usuario:deleteUsuario }

deleteAdmin:
    path:     /deleteAdmin/{idUsu}
    defaults: { _controller: toosistemadeventasBundle:Usuario:deleteAdmin }
file:
    path:     /regPendiente
    defaults: { _controller: toosistemadeventasBundle:Seguridad:registroProducto }

nuevoProducto:
    path:     /nuevoProducto
    defaults: { _controller: toosistemadeventasBundle:Productos:nuevoProducto }

editarProducto:
    path:     /editarProducto/{id}
    defaults: { _controller: toosistemadeventasBundle:Productos:editarProducto}

bajarProducto:
    path:     /bajarProducto/{id}
    defaults: { _controller: toosistemadeventasBundle:Productos:bajarProducto}
dql:
    path:     /dql
    defaults: { _controller: toosistemadeventasBundle:Default:DQL}