toosistemadeventas_homepage:
    path:     /hello/{name}
    defaults: { _controller: toosistemadeventasBundle:Default:index }

toosistemadeventas_inicio:
    path:     /inicio
    defaults: { _controller: toosistemadeventasBundle:Default:inicio }

toosistemadeventas_promociones:
    path:     /promociones
    defaults: { _controller: toosistemadeventasBundle:Default:promociones }

toosistemadeventas_registro:
    path:     /registro
    defaults: { _controller: toosistemadeventasBundle:Seguridad:registro }

login_form:
    path:     /login
    defaults: { _controller: toosistemadeventasBundle:Security:login }

logout:
    path:     /logout
    defaults: { _controller: toosistemadeventasBundle:Security:logout }

catalogo:
    path:     /catalogo
    defaults: { _controller: toosistemadeventasBundle:Default:catalogo }
