toosistemadeventas_homepage:
    path:     /hello/{name}
    defaults: { _controller: toosistemadeventasBundle:Default:index }

toosistemadeventas_inicio:
    path:     /inicio
    defaults: { _controller: toosistemadeventasBundle:Default:inicio }

debaja:
    path:     /usuarioNoExiste
    defaults: { _controller: toosistemadeventasBundle:Default:baja }

toosistemadeventas_promociones:
    path:     /promociones
    defaults: { _controller: toosistemadeventasBundle:Default:promociones }

toosistemadeventas_registro:
    path:     /registro
    defaults: { _controller: toosistemadeventasBundle:Seguridad:registro }

login_form:
    path:     /login
    defaults: { _controller: toosistemadeventasBundle:Security:login }

logout:
    path:     /logout
    defaults: { _controller: toosistemadeventasBundle:Security:logout }

#Catalogo
catalogo:
    path:     /catalogo
    defaults: { _controller: toosistemadeventasBundle:Default:catalogo }

#Administrador
inicioAdmin:
    path:     /inicioAdmin
    defaults: { _controller: toosistemadeventasBundle:Usuario:index }

crudAdmin:
    path:     /crudAdmin
    defaults: { _controller: toosistemadeventasBundle:Usuario:admin }

nuevoAdmin:
    path:     /nuevoAdmin
    defaults: { _controller: toosistemadeventasBundle:Usuario:nuevoAdmin }

editarAdmin:
    path:     /editarAdmin/{idUsu}
    defaults: { _controller: toosistemadeventasBundle:Usuario:editarAdmin }

deleteAdmin:
    path:     /deleteAdmin/{idUsu}
    defaults: { _controller: toosistemadeventasBundle:Usuario:deleteAdmin }

#Usuarios
editarUsuario:
    path:     /editarUsuario/{idUsu}
    defaults: { _controller: toosistemadeventasBundle:Usuario:editarUsuario }

allUsuarios:
    path:     /allUsuarios
    defaults: { _controller: toosistemadeventasBundle:Usuario:all }

crudUsuarios:
    path:     /crudUsuarios
    defaults: { _controller: toosistemadeventasBundle:Usuario:usuarios }

deleteUsuario:
    path:     /deleteUsuario/{idUsu}
    defaults: { _controller: toosistemadeventasBundle:Usuario:deleteUsuario }

#Clientes
nuevoCliente:
    path:     /nuevoCliente
    defaults: { _controller: toosistemadeventasBundle:Usuario:nuevoCliente }

crudClientes:
    path:     /crudClientes
    defaults: { _controller: toosistemadeventasBundle:Usuario:clientes }

editarCliente:
    path:     /editarCliente/{idUsu}
    defaults: { _controller: toosistemadeventasBundle:Usuario:editarCliente}

#Archivo
file:
    path:     /regPendiente
    defaults: { _controller: toosistemadeventasBundle:Seguridad:registroProducto }

#Productos
productos:
    path:     /productos
    defaults: { _controller: toosistemadeventasBundle:Productos:productos }

nuevoProducto:
    path:     /nuevoProducto
    defaults: { _controller: toosistemadeventasBundle:Productos:nuevoProducto }

editarProducto:
    path:     /editarProducto/{id}
    defaults: { _controller: toosistemadeventasBundle:Productos:editarProducto}

bajarProducto:
    path:     /bajarProducto/{id}
    defaults: { _controller: toosistemadeventasBundle:Productos:cambiarEstado}

#Categorias

crudCat:
    path:     /crudCat
    defaults: { _controller: toosistemadeventasBundle:Categoria:crudCat }

deleteCat:
    path:     /deleteCat/{idCat}
    defaults: { _controller: toosistemadeventasBundle:Categoria:deleteCat }

editarCat:
    path:     /editarCat/{idCat}
    defaults: { _controller: toosistemadeventasBundle:Categoria:editarCat }

nuevaCat:
    path:     /nuevaCat
    defaults: { _controller: toosistemadeventasBundle:Categoria:nuevaCat }

#Carrito

carrito:
    path:     /carrito
    defaults: { _controller: toosistemadeventasBundle:Carrito:carrito }

insertarCar:
    path:     /insertarCar/{id}
    defaults: { _controller: toosistemadeventasBundle:Carrito:insertar }

editarCarrito:
    path:     /edCar
    defaults: { _controller: toosistemadeventasBundle:Carrito:editCarrito }

deleteCarrito:
    path:     /delCar/{id}
    defaults: { _controller: toosistemadeventasBundle:Carrito:deleteCarrito }

#Inventario

inventario:
    path:     /inventario
    defaults: { _controller: toosistemadeventasBundle:Inventario:inventario }

verifinventario:
    path:     /verifinventario/{id}
    defaults: { _controller: toosistemadeventasBundle:Inventario:verificar }

nuevoInventario:
    path:     /newInventario/{id}
    defaults: { _controller: toosistemadeventasBundle:Inventario:agregarInventario }

#Venta
venta:
    path:     /venta
    defaults: { _controller: toosistemadeventasBundle:Venta:venta }

vedido:
     path:     /vendidos
     defaults: { _controller: toosistemadeventasBundle:Venta:vendidos }

devoluciones:
     path:     /devoluciones
     defaults: { _controller: toosistemadeventasBundle:Venta:devoluciones }

#reportes
pdf:
    path:     /pdf
    defaults: { _controller: toosistemadeventasBundle:Reporte:pdf }

reportes:
    path:     /reportes
    defaults: { _controller: toosistemadeventasBundle:Reporte:reportes }

reporteClientes:
    path:     /reporteClientes
    defaults: { _controller: toosistemadeventasBundle:Reporte:reportesClientes }

reporteExistencias:
    path:     /reporteExistencias
    defaults: { _controller: toosistemadeventasBundle:Reporte:reporteExistencias }

reporteVentas:
    path:     /reporteVentas
    defaults: { _controller: toosistemadeventasBundle:Reporte:reporteVentas }

factura:
    path:     /factura
    defaults: { _controller: toosistemadeventasBundle:Reporte:factura }
#Compras
compras:
    path:     /compras
    defaults: { _controller: toosistemadeventasBundle:Venta:compras }
#Devoluciones
devolucion:
    path:     /devoluciones/{id}
    defaults: { _controller: toosistemadeventasBundle:Devoluciones:devolucion }
#configuracion
config:
    path:     /configuracion
    defaults: { _controller: toosistemadeventasBundle:Usuario:config}
bajaUser:
    path:     /bajaUser
    defaults: { _controller: toosistemadeventasBundle:Usuario:BajaUSer}
cambiarPass:
    path:     /cambioPass
    defaults: { _controller: toosistemadeventasBundle:Usuario:contraNueva}