<?php

namespace too\sistemadeventasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InventarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventarioRepository extends EntityRepository
{
    public function getProductosVendibles(){
        return $this->getEntityManager()->createQuery(
            'SELECT inv FROM toosistemadeventasBundle:Inventario inv WHERE inv.cantidadDisponible > inv.cantidadInicial'
        )
            ->getResult();
    }
}
